### ISSUE TITLE
mac下 pure server start －p 80 错误的解决方法

### ISSUE THREAD

**Issue by hymCode** [fex-team/fis-pure#32]
ACA8016C:shijianke hymCode$ pure server start -p 80
checking java support : v1.8.0
checking php-cgi support : unsupported php-cgi environment
starting fis-server ... fail
2015-11-12 02:28:21.967:INFO:oejs.Server:jetty-8.y.z-SNAPSHOT
2015-11-12 02:28:23.325:WARN:oejuc.AbstractLifeCycle:FAILED SelectChannelConnector@0.0.0.0:80: java.net.SocketException: Permission denied
java.net.SocketException: Permission denied
    at sun.nio.ch.Net.bind0(Native Method)
    at sun.nio.ch.Net.bind(Net.java:433)
    at sun.nio.ch.Net.bind(Net.java:425)
    at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
    at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
    at org.eclipse.jetty.server.nio.SelectChannelConnector.open(SelectChannelConnector.java:187)
    at org.eclipse.jetty.server.AbstractConnector.doStart(AbstractConnector.java:316)
    at org.eclipse.jetty.server.nio.SelectChannelConnector.doStart(SelectChannelConnector.java:265)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
    at org.eclipse.jetty.server.Server.doStart(Server.java:293)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
    at com.baidu.fis.HttpServer.<init>(HttpServer.java:87)
    at com.baidu.fis.HttpServer.main(HttpServer.java:52)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)

 [ERROR] fis-server fails to start at port [80], error: Permission denied
ACA8016C:shijianke hymCode$

**Comment by oxUnd** [comment]
```
Permission denied
```

系统 1024 以下的端口都是需要管理员权限的

**Comment by hymCode** [comment]
@xiangshouding  非常谢谢你， mac 刚入手 网上好像也没找到这个问题对应的解决方案， 有什么命令可以支持获取管理员权限吗？
